#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


def parse_value(raw):
    if isinstance(raw, int):
        return raw
    if isinstance(raw, str):
        return int(raw, 0)
    raise ValueError(f"Unsupported value type: {type(raw)!r}")


def to_u16(value):
    return value & 0xFFFF


def load_case(cases_path, case_name):
    data = json.loads(Path(cases_path).read_text(encoding="utf-8-sig"))
    all_cases = data.get("cases", [])
    for case in all_cases:
        if case.get("name") == case_name:
            return case
    known = ", ".join(sorted(c.get("name", "") for c in all_cases))
    raise ValueError(f"Case '{case_name}' not found. Known cases: {known}")


def validate_matrix(name, values):
    if len(values) != 16:
        raise ValueError(f"{name} must contain exactly 16 elements, got {len(values)}")
    return [parse_value(v) for v in values]


def render_array(name, values):
    lines = [f"static const uint32_t {name}[16] = {{"]
    for r in range(4):
        row = values[r * 4 : (r + 1) * 4]
        words = ", ".join(f"0x{to_u16(v):04x}u" for v in row)
        suffix = "," if r < 3 else ""
        lines.append(f"    {words}{suffix}")
    lines.append("};")
    return "\n".join(lines)


def render_header(case):
    name = case.get("name", "unknown")
    notes = case.get("notes", "No notes.")
    a_vals = validate_matrix("a_q5_10", case["a_q5_10"])
    b_vals = validate_matrix("b_q5_10", case["b_q5_10"])
    return "\n".join(
        [
            "/* Auto-generated by gen_case_header.py */",
            f"/* case: {name} */",
            f"/* notes: {notes} */",
            "",
            render_array("a_init", a_vals),
            "",
            render_array("b_init", b_vals),
            "",
        ]
    )


def main():
    parser = argparse.ArgumentParser(description="Generate firmware_case_data.h for a selected case.")
    parser.add_argument("--cases", required=True, help="Path to cases json")
    parser.add_argument("--case", required=True, help="Case name")
    parser.add_argument("--header-out", required=True, help="Output header path")
    args = parser.parse_args()

    case = load_case(args.cases, args.case)
    header_text = render_header(case)
    out_path = Path(args.header_out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header_text, encoding="utf-8")
    print(f"Generated case header for '{args.case}' at {out_path}")


if __name__ == "__main__":
    main()
