#!/usr/bin/env python3
"""
gen_custom_case.py
------------------
Convert real-valued 4x4 A/B matrices into Q5.10 and generate:
  1. tb/custom_case_data.vh      — Verilog localparams for tb_custom_case.v
  2. results/custom_cases/<name>_expected.json  — expected C in Q5.10 + real

Q5.10 rules:
  encode : q = round(real * 1024),  clamped to [-32768, 32767]
  decode : real = q / 1024.0
  multiply: product = a*b (32-bit), shift right 10, accumulate in 32-bit,
            output is lower 16 bits of accumulator — matches pe_cell_q5_10.v
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

Q_SCALE  = 1024
S16_MIN  = -32768
S16_MAX  =  32767
U16_MASK = 0xFFFF
S32_MASK = 0xFFFFFFFF
S32_SIGN = 0x80000000


def now_utc_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8-sig"))


def write_json(path, data):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def to_q5_10(real_val):
    """Convert real number to Q5.10 signed 16-bit integer (clamped)."""
    v = int(round(float(real_val) * Q_SCALE))
    return max(S16_MIN, min(S16_MAX, v))


def as_s16(raw_16bit):
    """Interpret a raw 16-bit value as signed."""
    v = raw_16bit & U16_MASK
    return v - 0x10000 if v >= 0x8000 else v


def as_s32(raw_32bit):
    """Interpret a raw 32-bit value as signed."""
    v = raw_32bit & S32_MASK
    return v - 0x100000000 if v >= S32_SIGN else v


def q5_10_mul(a_s16, b_s16):
    """
    Signed 16-bit Q5.10 multiply matching pe_cell_q5_10.v:
      product_full = $signed(x_in) * $signed(y_in)   [32-bit signed]
      product_q5_10 = product_full >>> 10             [arithmetic shift]
    Returns the full 32-bit shifted product (still needs accumulation).
    """
    product = a_s16 * b_s16          # Python handles signed correctly
    return as_s32(product) >> 10     # arithmetic right shift 10


def matmul_q5_10(A_flat, B_flat):
    """
    4x4 Q5.10 matrix multiply matching the RTL exactly:
      z_acc (32-bit) += product_q5_10 for each k
      c_flat[r*4+c] = z_acc[15:0]  (lower 16 bits, unsigned raw)
    A_flat, B_flat: 16 signed 16-bit Q5.10 values, row-major.
    Returns 16 unsigned 16-bit raw values (use as_s16() to get signed).
    """
    C_raw = []
    for r in range(4):
        for c in range(4):
            acc32 = 0
            for k in range(4):
                acc32 += q5_10_mul(A_flat[r * 4 + k], B_flat[k * 4 + c])
                acc32 = as_s32(acc32)   # keep in 32-bit signed range
            C_raw.append(acc32 & U16_MASK)   # lower 16 bits
    return C_raw


def flat_to_4x4(flat):
    return [[flat[r * 4 + c] for c in range(4)] for r in range(4)]


def main():
    ap = argparse.ArgumentParser(description="Generate custom Q5.10 case for rv32_pipeline")
    ap.add_argument("--input",     required=True,  help="Input JSON (a_real_4x4 / b_real_4x4)")
    ap.add_argument("--vh-out",    required=True,  help="Output .vh Verilog header path")
    ap.add_argument("--json-out",  required=True,  help="Output expected-C JSON path")
    ap.add_argument("--case-name", default="custom", help="Identifier string in outputs")
    args = ap.parse_args()

    data = load_json(args.input)

    # Parse A
    if "a_real_4x4" in data:
        A_flat = [to_q5_10(v) for row in data["a_real_4x4"] for v in row]
    elif "a_q5_10_flat" in data:
        A_flat = [int(v) for v in data["a_q5_10_flat"]]
    else:
        sys.exit("ERROR: input JSON must contain 'a_real_4x4' or 'a_q5_10_flat'")

    # Parse B
    if "b_real_4x4" in data:
        B_flat = [to_q5_10(v) for row in data["b_real_4x4"] for v in row]
    elif "b_q5_10_flat" in data:
        B_flat = [int(v) for v in data["b_q5_10_flat"]]
    else:
        sys.exit("ERROR: input JSON must contain 'b_real_4x4' or 'b_q5_10_flat'")

    if len(A_flat) != 16 or len(B_flat) != 16:
        sys.exit("ERROR: A and B must each have 16 elements (4x4)")

    # Compute expected C (matches RTL exactly)
    C_raw = matmul_q5_10(A_flat, B_flat)   # 16 unsigned 16-bit values

    # ── Generate Verilog header ──────────────────────────────────────────────
    lines = [
        "// custom_case_data.vh",
        f"// Auto-generated by gen_custom_case.py  case={args.case_name}",
        f"// {now_utc_iso()}  — DO NOT EDIT, regenerate with run_custom_case.ps1",
        "//",
        "// A_DATA_xx / B_DATA_xx : individual Q5.10 elements (signed 16-bit)",
        "// A_WORD_x  / B_WORD_x  : packed 32-bit words {odd_elem, even_elem}",
        "// EXP_C_xx              : expected C = A×B lower 16 bits",
        "",
    ]

    for i, v in enumerate(A_flat):
        lines.append(f"localparam signed [15:0] A_DATA_{i:02d} = 16'h{v & U16_MASK:04X};")
    lines.append("")

    for i, v in enumerate(B_flat):
        lines.append(f"localparam signed [15:0] B_DATA_{i:02d} = 16'h{v & U16_MASK:04X};")
    lines.append("")

    for i, v in enumerate(C_raw):
        lines.append(f"localparam [15:0] EXP_C_{i:02d} = 16'h{v:04X};")
    lines.append("")

    # Packed 32-bit words: {odd_element[15:0], even_element[15:0]}
    for i in range(8):
        lo = A_flat[i * 2]     & U16_MASK
        hi = A_flat[i * 2 + 1] & U16_MASK
        lines.append(f"localparam [31:0] A_WORD_{i} = 32'h{hi:04X}{lo:04X};")
    lines.append("")

    for i in range(8):
        lo = B_flat[i * 2]     & U16_MASK
        hi = B_flat[i * 2 + 1] & U16_MASK
        lines.append(f"localparam [31:0] B_WORD_{i} = 32'h{hi:04X}{lo:04X};")
    lines.append("")

    Path(args.vh_out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.vh_out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[gen_custom_case] Wrote {args.vh_out}")

    # ── Generate expected-C JSON ─────────────────────────────────────────────
    c_signed  = [as_s16(v) for v in C_raw]
    c_q5_10   = flat_to_4x4(c_signed)
    c_real    = [[round(v / Q_SCALE, 8) for v in row] for row in c_q5_10]

    a_signed  = [as_s16(v & U16_MASK) for v in A_flat]
    a_q5_10   = flat_to_4x4(a_signed)
    a_real    = [[round(v / Q_SCALE, 8) for v in row] for row in a_q5_10]

    b_signed  = [as_s16(v & U16_MASK) for v in B_flat]
    b_q5_10   = flat_to_4x4(b_signed)
    b_real    = [[round(v / Q_SCALE, 8) for v in row] for row in b_q5_10]

    out = {
        "case_name":        args.case_name,
        "generated_at_utc": now_utc_iso(),
        "q_format":         "Q5.10",
        "real_value_rule":  "real = q5_10 / 1024.0",
        "input": {
            "a_q5_10_4x4": a_q5_10,
            "a_real_4x4":  a_real,
            "b_q5_10_4x4": b_q5_10,
            "b_real_4x4":  b_real,
        },
        "expected_c": {
            "c_q5_10_4x4": c_q5_10,
            "c_real_4x4":  c_real,
        },
    }
    write_json(args.json_out, out)
    print(f"[gen_custom_case] Wrote {args.json_out}")


if __name__ == "__main__":
    main()
